### ISSUE TITLE
Separate permissions for different actions

### ISSUE THREAD

**Issue by RDIL** [SteveL-MSFT/PoshChan-Bot#12]
Hello
I was going to file an issue for @travisez13 here but I forgot what it is about 🤕 
https://github.com/PowerShell/PowerShell-Docker/pull/187#discussion_r267529754

**Comment by SteveL-MSFT** [comment]
Yup, thought about having separate permissions for different actions.  Will look into that.

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/SteveL-MSFT/PoshChan-Bot/pull/18
