### ISSUE TITLE
Allow project name to be configured for rebuild action

### ISSUE THREAD

**Issue by TravisEz13** [SteveL-MSFT/PoshChan-Bot#13]
See the discussion here:  https://github.com/PowerShell/PowerShell-Docker/pull/187#discussion_r267529754

How do we set the value of Project here: https://github.com/SteveL-MSFT/PoshChan-Bot/blob/f310dc44ec9ba6f6b4c5af433f31b78e7ff519e9/FunctionApp/AzDevOps-Rebuild/run.ps1#L5

I see... You cannot. It's hard coded to the github project name, here: https://github.com/SteveL-MSFT/PoshChan-Bot/blob/f310dc44ec9ba6f6b4c5af433f31b78e7ff519e9/FunctionApp/PoshChan-Bot/run.ps1#L53

**Comment by TravisEz13** [comment]
@RDIL

**Comment by RDIL** [comment]
oh right that was what I was going to open an issue for

**Comment by SteveL-MSFT** [comment]
The current code assumes the AzDevOps org matches the GitHub org and the project names also match.  Will make this configurable.

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/SteveL-MSFT/PoshChan-Bot/pull/18
