### ISSUE TITLE
Should not post errors because the job was cancelled

### ISSUE THREAD

**Issue by TravisEz13** [SteveL-MSFT/PoshChan-Bot#37]
See https://github.com/PowerShell/PowerShell/pull/9202#issuecomment-478283847

**Comment by TravisEz13** [comment]
https://powershell.visualstudio.com/PowerShell/_build/results?buildId=18648&view=results

**Comment by adityapatwardhan** [comment]
https://github.com/PowerShell/PowerShell/pull/9269
