### ISSUE TITLE
PoshChan bot often says I didn't say please when I did.

### ISSUE THREAD

**Issue by TravisEz13** [SteveL-MSFT/PoshChan-Bot#38]
https://github.com/PowerShell/PowerShell-Docker/pull/197#issuecomment-478286523

**Comment by SteveL-MSFT** [comment]
@TravisEz13 let me know if this is still happening

**Comment by SteveL-MSFT** [comment]
Trimming the matched command as that is the only thing I can see that would cause the matching to fail.  Closing this until there's a repro.
