### ISSUE TITLE
Reference Guide / Active Help responses

### ISSUE THREAD

**Issue by vexx32** [SteveL-MSFT/PoshChan-Bot#42]
you may want to add either:

- a MD help doc
- template response(s) for PoshChan for folks to use who are forgetful with the list of accepted commands and/or aliases 

so someone could e.g, `<@>PoshChan please help` or something along those lines.

Would be good to include accepted rebuild target names etc for users authorised to do those actions, for future-proofing.

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/SteveL-MSFT/PoshChan-Bot/pull/43
