### ISSUE TITLE
Self-delete outdated comments containing test failures

### ISSUE THREAD

**Issue by vexx32** [SteveL-MSFT/PoshChan-Bot#55]
Reporting of the test failures is _extremely_ helpful, but can easily get cluttered when tests are being run & failed a few times. It would be really helpful if PoshChan could mark its test reports as outdated or delete them before posting a new set of reports.

**Comment by SteveL-MSFT** [comment]
I reached out to GitHub as their REST API currently doesn't support this.  However, I believe this PR resolves this issue somewhat: https://github.com/SteveL-MSFT/PoshChan-Bot/pull/56

**Comment by vexx32** [comment]
Oh, yeah, that'll make it a _ton_ better. Thanks!

**Comment by JesusPeacekd** [comment]
Thanks
